[mypy]
python_version = 3.9
ignore_missing_imports = True
warn_return_any = True

# Ignora os erros em todos os módulos do projeto inicialmente
[mypy-qobuz_dl.*]
ignore_errors = True

# Habilita a checagem rigorosa apenas para o módulo db nesta etapa
[mypy-qobuz_dl.db]
ignore_errors = False